version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db_name
      POSTGRES_USER: my_db_user
      POSTGRES_PASSWORD: my_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
