# Generated by Django 5.0.7 on 2024-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='imap_server',
            field=models.CharField(default='imap.server.domain', max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='name',
            field=models.CharField(default='email_account', max_length=255),
        ),
    ]
