# Generated by Django 5.0.7 on 2024-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_emailmessage_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
